import type { Metadata } from "next";
import localFont from "next/font/local";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { StyledEngineProvider } from '@mui/material/styles';
import "./globals.css";
import '@fontsource/inter';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "KAI",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  // pageProps: { session, ...pageProps },
}: Readonly<{
  children: React.ReactNode,
  // pageProps: any
}>) {

  return (
    // <SessionProvider session={session}>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider>
          <StyledEngineProvider injectFirst>
            {children}
          </StyledEngineProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
    // </SessionProvider>
  );
}
