import type { Metadata } from "next";
import "../globals.css";
import '@fontsource/inter';
import BaseLayout from "../components/BaseLayout";

export const metadata: Metadata = {
  title: "KAI",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
  // pageProps: { session, ...pageProps },
}: Readonly<{
  children: React.ReactNode,
  // pageProps: any
}>) {

  return (
    // <SessionProvider session={session}>

    <BaseLayout>
      {children}
    </BaseLayout>

    // </SessionProvider>
  );
}
